spring:
  config:
    import: aws-parameterstore:/member-profile-api/prod/

  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  servlet:
    multipart:
      max-file-size: 10MB

  h2:
    console:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: ${S3_BUCKET_NAME}

management:
  endpoint:
    health:
      show-details: never
  info:
    env:
      enabled: true

info:
  team:
    name: ${TEAM_NAME}